namespace Moria.Core.Structures.Enumerations
{
    public enum MageSpellId
    {
        MagicMissile = 1,
        DetectMonsters,
        PhaseDoor,
        LightArea,
        CureLightWounds,
        FindHiddenTrapsDoors,
        StinkingCloud,
        Confusion,
        LightningBolt,
        TrapDoorDestruction,
        Sleep1,
        CurePoison,
        TeleportSelf,
        RemoveCurse,
        FrostBolt,
        WallToMud,
        CreateFood,
        RechargeItem1,
        Sleep2,
        PolymorphOther,
        IdentifyItem,
        Sleep3,
        FireBolt,
        SpeedMonster,
        FrostBall,
        RechargeItem2,
        TeleportOther,
        HasteSelf,
        FireBall,
        WordOfDestruction,
        Genocide,
    };
}
