//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moria.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataFilesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataFilesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moria.Core.Resources.DataFilesResource", typeof(DataFilesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                                     #
        ///                                   #####
        ///                                     #
        ///                               ,,,  $$$  ,,,
        ///                           ,,=$   &quot;$$$$$&quot;   $=,,
        ///                         ,$$        $$$        $$,
        ///                         *&gt;         &lt;*&gt;         &lt;*
        ///                         $$         $$$         $$
        ///                         &quot;$$        $$$        $$&quot;
        ///                          &quot;$$       $$$       $$&quot;
        ///                           *##### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string death_royal {
            get {
                return ResourceManager.GetString("death_royal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///               _______________________
        ///              /                       \         ___
        ///             /                         \ ___   /   \      ___
        ///            /            RIP            \   \  :   :     /   \
        ///           /                             \  : _;,,,;_    :   :
        ///          /                               \,;_          _;,,,;_
        ///         |               the               |   ___
        ///         |                                 |  /   \
        ///         |                                 |  :   :
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string death_tomb {
            get {
                return ResourceManager.GetString("death_tomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Summary (@ is optional count, ~ is direction, ^R redraws, ESC aborts)
        ///  a        Aim and fire a wand          | @ B ~      Bash item or monster
        ///  b        Browse a book               |   C        Character description
        ///  c ~      Close a door                | @ D ~      Disarm a trap/chest
        ///  d        Drop an item                |   E        Eat some food
        ///  e        Equipment list              |   F        Fill lamp with oil
        ///  f        Fire/Throw an item          |   G        Gain new magic spel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :  - Map area (panel)
        ///^A - Cure all maladies and remove curses
        ///^B - Print random objects sample to file
        ///^D - Jump to depth # (level)
        ///^E - Edit character stats
        ///^F - Vanquish monsters within sight
        ///^G - Generate random items
        ///^H - Wizard Help
        ///^I - Identify an item
        ///^L - Wizard light
        ///^T - Teleport player randomly
        ///^U - Summon random monster
        ///^W - Wizard mode on/off
        ///+  - Gain experience
        ///%  - Generate a dungeon item
        ///@  - Create an object *CAN CAUSE FATAL ERROR*
        ///.
        /// </summary>
        internal static string help_wizard {
            get {
                return ResourceManager.GetString("help_wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     GNU GENERAL PUBLIC LICENSE
        ///                       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
        /// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Publi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Summary (@ is optional count, ~ is direction, ^R redraws, ESC aborts)
        ///  c ~     Close a door              |   C       Character description
        ///  d       Drop an item              | @ D ~     Disarm a trap/chest
        ///  e       Equipment list            |   E       Eat some food
        ///@ f ~     Force (bash) item or mons.|   F       Fill lamp with oil
        ///  i       Inventory list            |   G       Gain new magic spells
        ///  m       Magic spell casting       |   M       Map (shown reduced size)
        ///@ o ~     Open a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rl_help {
            get {
                return ResourceManager.GetString("rl_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \  - Wizard Help
        ///:  - Map area (panel)
        ///*  - Wizard light
        ///^A - Cure all maladies and remove curses
        ///^D - Jump to depth # (level)
        ///^E - Edit character stats
        ///^F - Vanquish monsters within sight
        ///^G - Generate random items
        ///^I - Identify an item
        ///^O - Print random objects sample to file
        ///^T - Teleport player randomly
        ///^W - Wizard mode on/off
        ///+  - Gain experience
        ///&amp;  - Summon random monster
        ///%  - Generate a dungeon item
        ///@  - Create an object *CAN CAUSE FATAL ERROR*
        ///.
        /// </summary>
        internal static string rl_help_wizard {
            get {
                return ResourceManager.GetString("rl_help_wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                    Robert A. Koeneke&apos;s classic roguelike
        ///
        ///
        ///             ##     ##    #######    ########    ####      ###
        ///             ###   ###   ##     ##   ##     ##    ##      ## ##
        ///             #### ####   ##     ##   ##     ##    ##     ##   ##
        ///             ## ### ##   ##     ##   ########     ##    ##     ##
        ///             ##     ##   ##     ##   ##   ##      ##    #########
        ///             ##     ##   ##     ##   ##    ##     ##    ##     ##
        ///             ##     ##    #######    ##     ##   ####   ##    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string splash {
            get {
                return ResourceManager.GetString("splash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                           Umoria 5.7.11  (2020-02-26)
        ///
        ///Previous major releases:
        ///
        ///            2016-11-27 : v5.7.0
        ///            2008-10-13 : v5.6.0
        ///            1994-07-21 : v5.5.2
        ///            1992-08-13 : v5.5.0
        ///            1991-10-12 : v5.4.0
        ///            1991-03-25 : v5.3.0
        ///            1990-05-09 : v5.2.0
        ///            1989-02-26 : v5.0.0
        ///            1988-05-26 : v4.87
        ///            1987-10-26 : v4.85
        ///
        ///Maintainer: David J. Grabiner (grabiner@alumni.princeton.edu)
        ///
        ///Umoria 5.7.x developed and maintained by Michael  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string versions {
            get {
                return ResourceManager.GetString("versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                        Welcome to Moria!
        ///
        ///Your first task is to generate a character. You must specify a gender,
        ///a race, and a class. Anytime before you have made these specifications,
        ///you can interrupt with control-C. You can also specify the race as
        ///often as you like by entering &apos;%&apos; to the class request. This will also
        ///regenerate your attributes.
        ///
        ///If this is your first time playing, you may want to read the manual first.
        ///.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
